#!/usr/bin/php -c/etc/phpd.ini
<?php
require 'config.php';

chdir(DAEMON_ROOT);

if(PHP_SAPI !== 'cli') {
    exit;
}

if (DAEMON_FORK && 0 !== pcntl_fork()) {
    exit;
}

Main::log(E_NOTICE, DAEMON_NAME . " started at " . date(DATE_RFC822));
